### ISSUE TITLE
Toto

### ISSUE THREAD

**Issue by Lodifice** [Lodifice/final-countdown#16]
I want `Africa` to be changed to `Hold the Line` instead, or maybe exclude Toto as they don't have that _one_ song. Both were pretty successful.

Change my mind!

**Comment by MarauderXtreme** [comment]
In the last few months `Africa` gained a lot of traction meme-wise. Since this is more or less a collection of meme songs I think I hereby stand to my decision to include `Africa` instead of `Hold the Line`.

**Comment by Lodifice** [comment]
I agree to your argumemes.
